#!/bin/bash

set -e

if [ -z "$1" ]; then
    echo "Usage: $0 file.chk"
    exit 1
fi

BASENAME="${1%.chk}"

CHKFILE="${BASENAME}.chk"
FCHKFILE="${BASENAME}.fchk"
SLURMFILE="${BASENAME}.slurm"

cat > "$SLURMFILE" <<EOF
#!/bin/bash

#SBATCH --nodes=1
#SBATCH --tasks-per-node=12
#SBATCH --time=72:00:00
#SBATCH --mem-per-cpu=3gb
#SBATCH -p plgrid
#SBATCH -A plgcalcs4spect2026-cpu
#SBATCH --job-name=formchk_${BASENAME}

module add gaussian/g16.C.01

formchk $CHKFILE $FCHKFILE
EOF

echo "Created $SLURMFILE"

# Submit the job
sbatch "$SLURMFILE"
echo "Submitted job for $CHKFILE"